/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: 'en';
  globals: {
    'settings-general': SettingsGeneral;
    'sign-up-page': SignUpPage;
    home: Home;
    contact: Contact;
  };
  globalsSelect: {
    'settings-general': SettingsGeneralSelect<false> | SettingsGeneralSelect<true>;
    'sign-up-page': SignUpPageSelect<false> | SignUpPageSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: 'en' | 'zh-TW';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  content?: {
    [k: string]: unknown;
  } | null;
  meta?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    shareImage?: (string | null) | Media;
  } | null;
  _status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  meta?: T | {
    metaTitle?: T;
    metaDescription?: T;
    shareImage?: T;
  };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  _uuid?: T;
}
/**
 * SettingsGeneral global
 */
export interface SettingsGeneral {
  id: string;
  siteTitle?: string | null;
  shareGraphic?: (string | null) | Media;
  shareVideo?: (string | null) | Media;
  favicon?: (string | null) | Media;
  faviconLight?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
export interface SettingsGeneralSelect<T extends boolean = true> {
  siteTitle?: T;
  shareGraphic?: T;
  shareVideo?: T;
  favicon?: T;
  faviconLight?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * SignUpPage global
 */
export interface SignUpPage {
  id: string;
  title?: string | null;
  slug?: string | null;
  policyMessage?: {
    [k: string]: unknown;
  } | null;
  meta?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    shareImage?: (string | null) | Media;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
export interface SignUpPageSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  policyMessage?: T;
  meta?: T | {
    metaTitle?: T;
    metaDescription?: T;
    shareImage?: T;
  };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Home global
 */
export interface Home {
  id: string;
  title?: string | null;
  content?: {
    [k: string]: unknown;
  } | null;
  meta?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    shareImage?: (string | null) | Media;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
export interface HomeSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  meta?: T | {
    metaTitle?: T;
    metaDescription?: T;
    shareImage?: T;
  };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact global
 */
export interface Contact {
  id: string;
  title?: string | null;
  slug?: string | null;
  contactForm?: {
    formTitle?: string | null;
    successMessage?: string | null;
    errorMessage?: string | null;
    sendToEmail?: string | null;
    emailSubject?: string | null;
    formFailureNotificationEmail?: string | null;
  } | null;
  meta?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    shareImage?: (string | null) | Media;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
export interface ContactSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  contactForm?: T | {
    formTitle?: T;
    successMessage?: T;
    errorMessage?: T;
    sendToEmail?: T;
    emailSubject?: T;
    formFailureNotificationEmail?: T;
  };
  meta?: T | {
    metaTitle?: T;
    metaDescription?: T;
    shareImage?: T;
  };
  updatedAt?: T;
  createdAt?: T;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}